version: '3.1'

services:
  app:
    container_name: tcc-pos-frontend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
    networks:
      - tcc-pos-net
    command: "npm run dev"

  nginx_proxy:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf # Mount your Nginx configuration
    networks:
      - tcc-pos-net
    depends_on:
      - app

networks:
  tcc-pos-net:
    external: true